# Generated by Django 5.0.2 on 2024-02-28 05:56

import app.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("role", models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name="NewsFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=4000, null=True)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OrderID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20, unique=True)),
                ("description", models.TextField(default="")),
                ("daily_earnings", models.IntegerField(default=0)),
                ("cycles", models.IntegerField(default=25)),
                ("quantity_limit", models.IntegerField(default=3)),
                ("minimum_withdrawal", models.IntegerField(default=300)),
                ("cost", models.IntegerField(default=0)),
                ("image", models.CharField(default="", max_length=2000)),
                ("vip_status", models.BooleanField(default=False)),
                ("discounted", models.BooleanField(default=False)),
                ("from_price", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_code", models.CharField(max_length=4000, null=True)),
                ("mpesa_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(default="", max_length=50)),
                (
                    "start_time",
                    models.TimeField(default=datetime.time(8, 56, 5, 811364)),
                ),
                (
                    "end_time",
                    models.TimeField(default=datetime.time(13, 56, 5, 811364)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=50)),
                ("message", models.TextField(null=True)),
                ("time_stamp", models.DateTimeField(default=app.models.default_now)),
                ("reply", models.BooleanField(default=False)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PendingRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=50)),
                ("amount", models.FloatField(default=0.0)),
                ("complete", models.BooleanField(default=False)),
                ("time_stamp", models.DateTimeField(default=app.models.default_now)),
                (
                    "order_id",
                    models.CharField(
                        default=app.models.calculate_order_id, max_length=50
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.receiveraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("amount", models.FloatField(default=0.0)),
                ("complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=app.models.default_now)),
                (
                    "mpesa_code",
                    models.CharField(default="", max_length=20, unique=True),
                ),
                ("mpesa_name", models.CharField(default="", max_length=100)),
                ("order_id", models.CharField(default="", max_length=50)),
                (
                    "receiver_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.receiveraccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_username", models.CharField(max_length=50, null=True)),
                ("child_username", models.CharField(max_length=50, null=True)),
                ("created_at", models.DateTimeField(default=app.models.default_now)),
                ("last_buy", models.DateTimeField(null=True)),
                ("first_product", models.BooleanField(default=False)),
                (
                    "child",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelectedReceiverAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.receiveraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=50)),
                ("created_at", models.DateTimeField(default=app.models.default_now)),
                (
                    "time_of_last_pay_off",
                    models.DateTimeField(default=app.models.default_now),
                ),
                ("days_amount", models.FloatField(default=0.0)),
                ("number_of_weekends", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("transaction_type", models.CharField(default="", max_length=20)),
                ("time_stamp", models.DateTimeField(default=app.models.default_now)),
                (
                    "transaction_code",
                    models.CharField(default=app.models.tc_calculate, max_length=20),
                ),
                ("description", models.TextField(default="")),
                ("amount", models.FloatField(default=0.0)),
                ("account_balance", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=200)),
                ("phone", models.CharField(default="", max_length=20)),
                ("balance", models.FloatField(default=0.0)),
                ("points", models.FloatField(default=0.0)),
                (
                    "referral_code",
                    models.CharField(
                        default=app.models.generate_random_string, max_length=2000
                    ),
                ),
                ("total_referrals", models.IntegerField(default=0)),
                ("active_subscriptions", models.IntegerField(default=0)),
                ("last_subscription_payoff", models.DateTimeField(null=True)),
                ("subscribed_referrals", models.IntegerField(default=0)),
                (
                    "last_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default="", max_length=50)),
                ("amount", models.IntegerField(default=300)),
                ("time_stamp", models.DateTimeField(default=app.models.default_now)),
                ("complete", models.BooleanField(default=False)),
                ("mpesa_number", models.CharField(default="", max_length=20)),
                ("mpesa_name", models.CharField(default="", max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
